// ... existing code up to 'me' entry ...

const WHOIS_SERVERS = {
  aaa: ["whois.nic.aaa"],
  aarp: ["whois.aarp"],
  abarth: ["whois.afilias-srs.net"],
  abb: ["whois.afilias-srs.net"],
  abbott: ["whois.afilias-srs.net"],
  abbvie: ["whois.afilias-srs.net"],
  abc: ["whois.afilias-srs.net"],
  able: ["whois.afilias-srs.net"],
  abogado: ["whois.nic.abogado"],
  ac: ["whois.nic.ac"],
  academy: ["whois.nic.academy"],
  accenture: ["whois.afilias-srs.net"],
  accountant: ["whois.nic.accountant"],
  accountancy: ["whois.nic.accountancy"],
  accountants: ["whois.nic.accountants"],
  aco: ["whois.nic.aco"],
  actor: ["whois.nic.actor"],
  ad: ["whois.nic.ad"],
  ads: ["whois.nic.ads"],
  adult: ["whois.nic.adult"],
  ae: ["whois.aeda.ae.net"],
  aero: ["whois.aero"],
  af: ["whois.nic.af"],
  afamilycompany: ["whois.nic.afamilycompany"],
  ag: ["whois.nic.ag"],
  agakhan: ["whois.nic.agakhan"],
  agency: ["whois.nic.agency"],
  ai: ["whois.nic.ai"],
  aig: ["whois.afilias-srs.net"],
  airbus: ["whois.afilias-srs.net"],
  airforce: ["whois.nic.airforce"],
  aircare: ["whois.nic.aircare"],
  airtel: ["whois.nic.airtel"],
  akdn: ["whois.nic.akdn"],
  al: ["whois.rit.al"],
  alfaromeo: ["whois.afilias-srs.net"],
  alibaba: ["whois.nic.alibaba"],
  alipay: ["whois.nic.alipay"],
  allfinanz: ["whois.nic.allfinanz"],
  allstate: ["whois.afilias-srs.net"],
  ally: ["whois.nic.ally"],
  alsace: ["whois.nic.alsace"],
  alstom: ["whois.afilias-srs.net"],
  am: ["whois.amnic.net"],
  americanexpress: ["whois.afilias-srs.net"],
  americanfamily: ["whois.nic.americanfamily"],
  amex: ["whois.afilias-srs.net"],
  amfam: ["whois.nic.amfam"],
  amica: ["whois.nic.amica"],
  amsterdam: ["whois.nic.amsterdam"],
  analytics: ["whois.nic.analytics"],
  android: ["whois.nic.android"],
  ao: ["whois.nic.ao"],
  apartments: ["whois.nic.apartments"],
  app: ["whois.nic.app"],
  apple: ["whois.afilias-srs.net"],
  aquarelle: ["whois.nic.aquarelle"],
  ar: ["whois.nic.ar"],
  arab: ["whois.nic.arab"],
  aramco: ["whois.nic.aramco"],
  archi: ["whois.nic.archi"],
  army: ["whois.nic.army"],
  arte: ["whois.nic.arte"],
  art: ["whois.nic.art"],
  arte: ["whois.nic.arte"],
  as: ["whois.nic.as"],
  asia: ["whois.nic.asia"],
  associates: ["whois.nic.associates"],
  at: ["whois.nic.at"],
  athleta: ["whois.nic.athleta"],
  attorney: ["whois.nic.attorney"],
  au: ["whois.aunic.net"],
  auction: ["whois.nic.auction"],
  audi: ["whois.nic.audi"],
  audible: ["whois.nic.audible"],
  audio: ["whois.nic.audio"],
  auspost: ["whois.nic.auspost"],
  author: ["whois.nic.author"],
  auto: ["whois.nic.auto"],
  autos: ["whois.nic.autos"],
  aw: ["whois.nic.aw"],
  aws: ["whois.nic.aws"],
  ax: ["whois.ax"],
  axa: ["whois.nic.axa"],
  az: ["whois.cfitp.az"],
  azure: ["whois.nic.azure"],
  ba: ["whois.herit.ba"],
  baby: ["whois.nic.baby"],
  baidu: ["whois.nic.baidu"],
  banamex: ["whois.nic.banamex"],
  bananarepublic: ["whois.nic.bananarepublic"],
  band: ["whois.nic.band"],
  bank: ["whois.nic.bank"],
  bar: ["whois.nic.bar"],
  barcelona: ["whois.nic.barcelona"],
  barclaycard: ["whois.nic.barclaycard"],
  barclays: ["whois.nic.barclays"],
  barefoot: ["whois.nic.barefoot"],
  bargains: ["whois.nic.bargains"],
  baseball: ["whois.nic.baseball"],
  basketball: ["whois.nic.basketball"],
  bauhaus: ["whois.nic.bauhaus"],
  bayern: ["whois.nic.bayern"],
  bb: ["whois.bb"],
  bbc: ["whois.afilias-srs.net"],
  bbt: ["whois.nic.bbt"],
  bbva: ["whois.nic.bbva"],
  bcg: ["whois.nic.bcg"],
  bcn: ["whois.nic.bcn"],
  bd: ["whois.nic.bd"],
  be: ["whois.nic.be"],
  beats: ["whois.nic.beats"],
  beauty: ["whois.nic.beauty"],
  beer: ["whois.nic.beer"],
  bentley: ["whois.nic.bentley"],
  berlin: ["whois.nic.berlin"],
  best: ["whois.nic.best"],
  bestbuy: ["whois.nic.bestbuy"],
  bet: ["whois.afilias-srs.net"],
  bf: ["whois.nic.bf"],
  bg: ["whois.register.bg"],
  bh: ["whois.nic.bh"],
  bharti: ["whois.afilias-srs.net"],
  bi: ["whois.nic.bi"],
  bible: ["whois.nic.bible"],
  bid: ["whois.nic.bid"],
  bike: ["whois.nic.bike"],
  bingo: ["whois.nic.bingo"],
  bio: ["whois.nic.bio"],
  biz: ["whois.biz"],
  bj: ["whois.nic.bj"],
  black: ["whois.nic.black"],
  blackfriday: ["whois.afilias-srs.net"],
  blockbuster: ["whois.nic.blockbuster"],
  blog: ["whois.nic.blog"],
  bloomberg: ["whois.nic.bloomberg"],
  blue: ["whois.nic.blue"],
  bm: ["whois.nic.bm"],
  bms: ["whois.nic.bms"],
  bmw: ["whois.nic.bmw"],
  bn: ["whois.bnnic.bn", "whois.bn", "whois.iana.org"],
  bnpparibas: ["whois.nic.bnpparibas"],
  bo: ["whois.nic.bo"],
  boats: ["whois.nic.boats"],
  boehringer: ["whois.nic.boehringer"],
  bofa: ["whois.nic.bofa"],
  bom: ["whois.nic.bom"],
  bond: ["whois.nic.bond"],
  boo: ["whois.nic.boo"],
  book: ["whois.nic.book"],
  booking: ["whois.nic.booking"],
  bosch: ["whois.bosch"],
  bostik: ["whois.nic.bostik"],
  boston: ["whois.nic.boston"],
  bot: ["whois.nic.bot"],
  boutique: ["whois.nic.boutique"],
  box: ["whois.nic.box"],
  br: ["whois.registro.br"],
  bradesco: ["whois.nic.bradesco"],
  bridgestone: ["whois.nic.bridgestone"],
  broadway: ["whois.nic.broadway"],
  broker: ["whois.nic.broker"],
  brother: ["whois.nic.brother"],
  brussels: ["whois.nic.brussels"],
  bs: ["whois.nic.bs"],
  bt: ["whois.nic.bt"],
  budapest: ["whois.nic.budapest"],
  budlight: ["whois.nic.budlight"],
  build: ["whois.nic.build"],
  builders: ["whois.afilias-srs.net"],
  business: ["whois.nic.business"],
  buy: ["whois.nic.buy"],
  buzz: ["whois.nic.buzz"],
  bv: ["whois.nic.bv"],
  bw: ["whois.nic.bw"],
  by: ["whois.cctld.by"],
  bz: ["whois2.belizenic.bz"],
  bzh: ["whois.nic.bzh"],
  ca: ["whois.cira.ca"],
  cab: ["whois.nic.cab"],
  cafe: ["whois.nic.cafe"],
  cal: ["whois.nic.cal"],
  call: ["whois.nic.call"],
  calvinklein: ["whois.nic.calvinklein"],
  cam: ["whois.nic.cam"],
  camera: ["whois.nic.camera"],
  camp: ["whois.nic.camp"],
  cano: ["whois.nic.canon"],
  capetown: ["whois.nic.capetown"],
  capital: ["whois.nic.capital"],
  capitalone: ["whois.nic.capitalone"],
  car: ["whois.nic.car"],
  caravan: ["whois.nic.caravan"],
  cards: ["whois.nic.cards"],
  care: ["whois.nic.care"],
  career: ["whois.nic.career"],
  careers: ["whois.nic.careers"],
  cars: ["whois.nic.cars"],
  casa: ["whois.nic.casa"],
  case: ["whois.nic.case"],
  caseih: ["whois.nic.caseih"],
  cash: ["whois.nic.cash"],
  casino: ["whois.nic.casino"],
  cat: ["whois.cat"],
  catering: ["whois.nic.catering"],
  catholic: ["whois.nic.catholic"],
  cba: ["whois.nic.cba"],
  cbn: ["whois.cbn.com.br"],
  cbn: ["whois.nic.cbn"],
  cbre: ["whois.nic.cbre"],
  cbs: ["whois.afilias-srs.net"],
  cc: ["whois.nic.cc"],
  cd: ["whois.nic.cd"],
  ceb: ["whois.nic.ceb"],
  center: ["whois.nic.center"],
  ceo: ["whois.nic.ceo"],
  cern: ["whois.nic.cern"],
  cf: ["whois.nic.cf"],
  cfa: ["whois.ausregistry.net.au"],
  cfd: ["whois.nic.cfd"],
  cg: ["whois.nic.cg"],
  ch: ["whois.nic.ch"],
  channel: ["whois.nic.channel"],
  charity: ["whois.afilias-srs.net"],
  chase: ["whois.nic.chase"],
  chat: ["whois.nic.chat"],
  cheap: ["whois.nic.cheap"],
  chintai: ["whois.nic.chintai"],
  christmas: ["whois.nic.christmas"],
  chrome: ["whois.nic.chrome"],
  church: ["whois.nic.church"],
  ci: ["whois.nic.ci"],
  cipriani: ["whois.nic.cipriani"],
  circle: ["whois.nic.circle"],
  cisco: ["whois.nic.cisco"],
  citadel: ["whois.nic.citadel"],
  citi: ["whois.nic.citi"],
  citic: ["whois.nic.citic"],
  city: ["whois.nic.city"],
  ck: ["whois.nic.ck"],
  cl: ["whois.nic.cl"],
  claims: ["whois.nic.claims"],
  cleaning: ["whois.nic.cleaning"],
  click: ["whois.nic.click"],
  clinic: ["whois.nic.clinic"],
  clinique: ["whois.nic.clinique"],
  clothing: ["whois.nic.clothing"],
  cloud: ["whois.nic.cloud"],
  club: ["whois.nic.club"],
  clubmed: ["whois.nic.clubmed"],
  cm: ["whois.nic.cm"],
  cn: ["whois.cnnic.cn"],
  co: ["whois.nic.co"],
  coach: ["whois.nic.coach"],
  codes: ["whois.nic.codes"],
  coffee: ["whois.nic.coffee"],
  college: ["whois.nic.college"],
  cologne: ["whois.nic.cologne"],
  com: ["whois.verisign-grs.com"],
  comcast: ["whois.nic.comcast"],
  commbank: ["whois.nic.commbank"],
  community: ["whois.nic.community"],
  company: ["whois.nic.company"],
  compare: ["whois.nic.compare"],
  computer: ["whois.nic.computer"],
  comsec: ["whois.nic.comsec"],
  condos: ["whois.nic.condos"],
  construction: ["whois.nic.construction"],
  consulting: ["whois.nic.consulting"],
  contact: ["whois.nic.contact"],
  contractors: ["whois.nic.contractors"],
  cooking: ["whois.nic.cooking"],
  cookingchannel: ["whois.nic.cookingchannel"],
  cool: ["whois.nic.cool"],
  coop: ["whois.nic.coop"],
  corsica: ["whois.nic.corsica"],
  country: ["whois.nic.country"],
  coupon: ["whois.nic.coupon"],
  coupons: ["whois.nic.coupons"],
  courses: ["whois.nic.courses"],
  cr: ["whois.nic.cr"],
  credit: ["whois.nic.credit"],
  creditcard: ["whois.nic.creditcard"],
  creditunion: ["whois.nic.creditunion"],
  cricket: ["whois.nic.cricket"],
  crown: ["whois.nic.crown"],
  crs: ["whois.crsnic.net"],
  cruise: ["whois.nic.cruise"],
  cucinelli: ["whois.nic.cucinelli"],
  cu: ["whois.nic.cu"],
  cuisine: ["whois.nic.cuisine"],
  cv: ["whois.nic.cv"],
  cw: ["whois.nic.cw"],
  cx: ["whois.nic.cx"],
  cy: ["whois.nic.cy"],
  cymru: ["whois.nic.cymru"],
  cyou: ["whois.nic.cyou"],
  cz: ["whois.nic.cz"],
  dabur: ["whois.nic.dabur"],
  dad: ["whois.nic.dad"],
  dance: ["whois.nic.dance"],
  data: ["whois.nic.data"],
  date: ["whois.nic.date"],
  dating: ["whois.nic.dating"],
  datsun: ["whois.nic.datsun"],
  day: ["whois.nic.day"],
  dclk: ["whois.nic.dclk"],
  dds: ["whois.nic.dds"],
  de: ["whois.denic.de"],
  deal: ["whois.nic.deal"],
  dealer: ["whois.nic.dealer"],
  deals: ["whois.nic.deals"],
  degree: ["whois.nic.degree"],
  delivery: ["whois.nic.delivery"],
  dell: ["whois.nic.dell"],
  deloitte: ["whois.nic.deloitte"],
  delta: ["whois.nic.delta"],
  democrat: ["whois.afilias-srs.net"],
  dental: ["whois.nic.dental"],
  dentist: ["whois.nic.dentist"],
  desi: ["whois.nic.desi"],
  design: ["whois.nic.design"],
  dev: ["whois.nic.dev"],
  dhl: ["whois.nic.dhl"],
  diamonds: ["whois.nic.diamonds"],
  diet: ["whois.nic.diet"],
  digital: ["whois.nic.digital"],
  direct: ["whois.nic.direct"],
  directory: ["whois.nic.directory"],
  discount: ["whois.nic.discount"],
  discover: ["whois.nic.discover"],
  dish: ["whois.nic.dish"],
  diy: ["whois.nic.diy"],
  dj: ["whois.nic.dj"],
  dk: ["whois.dk-hostmaster.dk"],
  dm: ["whois.nic.dm"],
  dnp: ["whois.nic.dnp"],
  do: ["whois.nic.do"],
  docs: ["whois.nic.docs"],
  doctor: ["whois.nic.doctor"],
  dodge: ["whois.nic.dodge"],
  dog: ["whois.nic.dog"],
  doha: ["whois.nic.doha"],
  dolla: ["whois.nic.dollar"],
  dolla: ["whois.nic.doll"],
  domains: ["whois.afilias-srs.net"],
  dot: ["whois.nic.dot"],
  download: ["whois.nic.download"],
  drive: ["whois.nic.drive"],
  dtv: ["whois.nic.dtv"],
  dubai: ["whois.nic.dubai"],
  ducker: ["whois.nic.duck"],
  durban: ["whois.nic.durban"],
  dvag: ["whois.nic.dvag"],
  dvr: ["whois.nic.dvr"],
  dz: ["whois.nic.dz"],
  ea: ["whois.nic.ea"],
  earth: ["whois.nic.earth"],
  eat: ["whois.nic.eat"],
  ec: ["whois.nic.ec"],
  eco: ["whois.afilias-srs.net"],
  edeka: ["whois.nic.edeka"],
  edu: ["whois.educause.edu"],
  education: ["whois.nic.education"],
  ee: ["whois.tld.ee"],
  eg: ["whois.ripe.net"],
  email: ["whois.nic.email"],
  emerck: ["whois.nic.emerck"],
  energy: ["whois.nic.energy"],
  engineer: ["whois.nic.engineer"],
  engineering: ["whois.nic.engineering"],
  enterprises: ["whois.nic.enterprises"],
  epson: ["whois.nic.epson"],
  equipment: ["whois.nic.equipment"],
  er: ["whois.ersnic.net"],
  erni: ["whois.nic.erni"],
  es: ["whois.nic.es"],
  esq: ["whois.nic.esq"],
  estate: ["whois.nic.estate"],
  et: ["whois.ethiotelecom.et"],
  etisalat: ["whois.nic.etisalat"],
  eu: ["whois.eu"],
  eurovision: ["whois.nic.eurovision"],
  eus: ["whois.nic.eus"],
  events: ["whois.nic.events"],
  everbank: ["whois.nic.everbank"],
  exchange: ["whois.nic.exchange"],
  expert: ["whois.nic.expert"],
  exposed: ["whois.nic.exposed"],
  express: ["whois.nic.express"],
  extraspace: ["whois.nic.extraspace"],
  fac: ["whois.nic.fairwinds"],
  fail: ["whois.nic.fail"],
  faith: ["whois.nic.faith"],
  family: ["whois.nic.family"],
  fan: ["whois.nic.fan"],
  fans: ["whois.nic.fans"],
  farm: ["whois.nic.farm"],
  farmers: ["whois.nic.farmers"],
  fashion: ["whois.nic.fashion"],
  fast: ["whois.nic.fast"],
  fedex: ["whois.nic.fedex"],
  feedback: ["whois.nic.feedback"],
  ferrari: ["whois.nic.ferrari"],
  ferrero: ["whois.nic.ferrero"],
  fi: ["whois.fi"],
  fidelity: ["whois.nic.fidelity"],
  fido: ["whois.nic.fido"],
  film: ["whois.nic.film"],
  final: ["whois.nic.final"],
  finance: ["whois.nic.finance"],
  financial: ["whois.nic.financial"],
  fire: ["whois.nic.fire"],
  firestone: ["whois.nic.firestone"],
  firmdale: ["whois.nic.firmdale"],
  fish: ["whois.nic.fish"],
  fishing: ["whois.nic.fishing"],
  fit: ["whois.nic.fit"],
  fitness: ["whois.nic.fitness"],
  fj: ["whois.usp.ac.fj"],
  fk: ["whois.nic.fk"],
  flickr: ["whois.nic.flickr"],
  flights: ["whois.nic.flights"],
  flir: ["whois.nic.flir"],
  florist: ["whois.nic.florist"],
  flowers: ["whois.nic.flowers"],
  fly: ["whois.nic.fly"],
  fm: ["whois.nic.fm"],
  fo: ["whois.nic.fo"],
  foo: ["whois.nic.foo"],
  food: ["whois.nic.food"],
  foodnetwork: ["whois.nic.foodnetwork"],
  football: ["whois.nic.football"],
  ford: ["whois.nic.ford"],
  foreclosure: ["whois.nic.foreclosure"],
  forgot: ["whois.nic.forgot"],
  foundation: ["whois.nic.foundation"],
  fox: ["whois.nic.fox"],
  fr: ["whois.nic.fr"],
  free: ["whois.nic.free"],
  fresenius: ["whois.nic.fresenius"],
  frl: ["whois.nic.frl"],
  frogans: ["whois.nic.frogans"],
  frontdoor: ["whois.nic.frontdoor"],
  frontier: ["whois.nic.frontier"],
  ftr: ["whois.nic.ftr"],
  fujitsu: ["whois.nic.fujitsu"],
  fun: ["whois.nic.fun"],
  fund: ["whois.nic.fund"],
  furniture: ["whois.nic.furniture"],
  futbol: ["whois.nic.futbol"],
  fyi: ["whois.nic.fyi"],
  ga: ["whois.nic.ga"],
  gal: ["whois.nic.gal"],
  gallery: ["whois.nic.gallery"],
  gallo: ["whois.nic.gallo"],
  gallup: ["whois.nic.gallup"],
  game: ["whois.nic.game"],
  games: ["whois.nic.games"],
  gap: ["whois.nic.gap"],
  garden: ["whois.nic.garden"],
  gay: ["whois.afilias-srs.net"],
  gb: ["whois.nic.uk"],
  gbiz: ["whois.nic.gbiz"],
  gd: ["whois.nic.gd"],
  gdn: ["whois.nic.gdn"],
  ge: ["whois.nic.ge"],
  gea: ["whois.nic.gea"],
  gent: ["whois.nic.gent"],
  genting: ["whois.nic.genting"],
  george: ["whois.nic.george"],
  gf: ["whois.nic.gf"],
  gg: ["whois.je"],
  ggee: ["whois.nic.ggee"],
  gh: ["whois.nic.gh"],
  gi: ["whois2.riponet.re"],
  gift: ["whois.nic.gift"],
  gifts: ["whois.nic.gifts"],
  gives: ["whois.nic.gives"],
  giving: ["whois.nic.giving"],
  gl: ["whois.nic.gl"],
  glass: ["whois.nic.glass"],
  gle: ["whois.nic.gle"],
  global: ["whois.nic.global"],
  globo: ["whois.nic.globo"],
  gm: ["whois.nic.gm"],
  gmail: ["whois.nic.gmail"],
  gmbh: ["whois.nic.gmbh"],
  gmo: ["whois.gmo"],
  gmx: ["whois.nic.gmx"],
  gn: ["whois.nic.gn"],
  godaddy: ["whois.nic.godaddy"],
  gold: ["whois.nic.gold"],
  goldpoint: ["whois.nic.goldpoint"],
  golf: ["whois.nic.golf"],
  goo: ["whois.nic.goo"],
  goodyear: ["whois.nic.goodyear"],
  goog: ["whois.nic.goog"],
  google: ["whois.nic.google"],
  gop: ["whois.nic.gop"],
  got: ["whois.nic.got"],
  gov: ["whois.nic.gov"],
  gp: ["whois.nic.gp"],
  gq: ["whois.dns.net.gq"],
  gr: ["whois.ics.forth.gr"],
  grainger: ["whois.nic.grainger"],
  graphics: ["whois.nic.graphics"],
  gratis: ["whois.nic.gratis"],
  green: ["whois.nic.green"],
  gripe: ["whois.nic.gripe"],
  grocery: ["whois.nic.grocery"],
  group: ["whois.nic.group"],
  gs: ["whois.nic.gs"],
  gt: ["whois.gt"],
  gu: ["whois.nic.gu"],
  guardian: ["whois.nic.guardian"],
  gucci: ["whois.nic.gucci"],
  guge: ["whois.nic.guge"],
  guide: ["whois.nic.guide"],
  guitars: ["whois.nic.guitars"],
  guru: ["whois.nic.guru"],
  gw: ["whois.nic.gw"],
  gy: ["whois.registry.gy"],
  hair: ["whois.nic.hair"],
  hamburg: ["whois.nic.hamburg"],
  hangout: ["whois.nic.hangout"],
  haus: ["whois.nic.haus"],
  hbo: ["whois.nic.hbo"],
  hdfc: ["whois.nic.hdfc"],
  hdfcbank: ["whois.nic.hdfcbank"],
  health: ["whois.nic.health"],
  healthcare: ["whois.nic.healthcare"],
  help: ["whois.nic.help"],
  helsinki: ["whois.nic.helsinki"],
  here: ["whois.nic.here"],
  hermes: ["whois.nic.hermes"],
  hiphop: ["whois.nic.hiphop"],
  hisamitsu: ["whois.nic.hisamitsu"],
  hitachi: ["whois.nic.hitachi"],
  hiv: ["whois.nic.hiv"],
  hk: ["whois.hkirc.hk"],
  hkt: ["whois.nic.hkt"],
  hm: ["whois.registry.hm"],
  hn: ["whois.nic.hn"],
  hockey: ["whois.nic.hockey"],
  holdings: ["whois.nic.holdings"],
  holiday: ["whois.nic.holiday"],
  homegoods: ["whois.nic.homegoods"],
  homes: ["whois.nic.homes"],
  homesense: ["whois.nic.homesense"],
  honda: ["whois.nic.honda"],
  horse: ["whois.nic.horse"],
  hospital: ["whois.nic.hospital"],
  host: ["whois.nic.host"],
  hosting: ["whois.nic.hosting"],
  hot: ["whois.nic.hot"],
  hoteles: ["whois.nic.hoteles"],
  hotels: ["whois.nic.hotels"],
  hotline: ["whois.nic.hotline"],
  house: ["whois.nic.house"],
  how: ["whois.nic.how"],
  hr: ["whois.dns.hr"],
  hsbc: ["whois.nic.hsbc"],
  ht: ["whois.nic.ht"],
  hu: ["whois.nic.hu"],
  hughes: ["whois.nic.hughes"],
  hyatt: ["whois.nic.hyatt"],
  hyundai: ["whois.nic.hyundai"],
  ibm: ["whois.nic.ibm"],
  icbc: ["whois.nic.icbc"],
  ice: ["whois.nic.ice"],
  ici: ["whois.nic.ici"],
  ieee: ["whois.nic.ieee"],
  ifm: ["whois.nic.ifm"],
  ikano: ["whois.nic.ikano"],
  il: ["whois.isoc.org.il"],
  im: ["whois.nic.im"],
  imamat: ["whois.nic.imamat"],
  imdb: ["whois.nic.imdb"],
  immo: ["whois.nic.immo"],
  immobilien: ["whois.nic.immobilien"],
  in: ["whois.inregistry.net"],
  industries: ["whois.nic.industries"],
  infiniti: ["whois.nic.infiniti"],
  info: ["whois.afilias.net"],
  ing: ["whois.nic.ing"],
  ink: ["whois.nic.ink"],
  institute: ["whois.nic.institute"],
  insurance: ["whois.nic.insurance"],
  insure: ["whois.nic.insure"],
  int: ["whois.iana.org"],
  international: ["whois.nic.international"],
  intuit: ["whois.nic.intuit"],
  investments: ["whois.nic.investments"],
  io: ["whois.nic.io"],
  ipiranga: ["whois.nic.ipiranga"],
  iq: ["whois.cmc.iq"],
  ir: ["whois.nic.ir"],
  is: ["whois.isnic.is"],
  ish: ["whois.nic.ish"],
  islam: ["whois.nic.islam"],
  island: ["whois.nic.island"],
  ist: ["whois.nic.ist"],
  istanbul: ["whois.nic.istanbul"],
  it: ["whois.nic.it"],
  itau: ["whois.nic.itau"],
  itv: ["whois.nic.itv"],
  jaguar: ["whois.nic.jaguar"],
  java: ["whois.nic.java"],
  jcb: ["whois.nic.jcb"],
  jcp: ["whois.nic.jcp"],
  je: ["whois.je"],
  jegs: ["whois.nic.jegs"],
  jetzt: ["whois.nic.jetzt"],
  jewelry: ["whois.nic.jewelry"],
  jio: ["whois.nic.jio"],
  jll: ["whois.nic.jll"],
  jm: ["whois.marjamcom.com"],
  jmp: ["whois.nic.jmp"],
  jnj: ["whois.nic.jnj"],
  jo: ["whois.dns.jo"],
  jobs: ["whois.nic.jobs"],
  joburg: ["whois.nic.joburg"],
  jot: ["whois.nic.jot"],
  joy: ["whois.nic.joy"],
  jp: ["whois.jprs.jp"],
  jpmorgan: ["whois.nic.jpmorgan"],
  jprs: ["whois.jprs.jp"],
  juegos: ["whois.nic.juegos"],
  juniper: ["whois.nic.juniper"],
  kaufen: ["whois.nic.kaufen"],
  kddi: ["whois.nic.kddi"],
  ke: ["whois.kenic.or.ke"],
  kerryhotels: ["whois.nic.kerryhotels"],
  kerrylogistics: ["whois.nic.kerrylogistics"],
  kerryproperties: ["whois.nic.kerryproperties"],
  kfh: ["whois.nic.kfh"],
  kg: ["whois.kg"],
  kh: ["whois.nic.kh"],
  ki: ["whois.nic.ki"],
  kia: ["whois.nic.kia"],
  kids: ["whois.nic.kids"],
  kim: ["whois.nic.kim"],
  kinder: ["whois.nic.kinder"],
  kindle: ["whois.nic.kindle"],
  kitchen: ["whois.nic.kitchen"],
  kiwi: ["whois.nic.kiwi"],
  km: ["whois.nic.km"],
  kn: ["whois.nic.kn"],
  koeln: ["whois.nic.koeln"],
  komatsu: ["whois.nic.komatsu"],
  kosher: ["whois.nic.kosher"],
  kp: ["whois.kcce.kp"],
  kpmg: ["whois.nic.kpmg"],
  kpn: ["whois.nic.kpn"],
  kr: ["whois.kr"],
  krd: ["whois.nic.krd"],
  kred: ["whois.nic.kred"],
  kuokgroup: ["whois.nic.kuokgroup"],
  kw: ["whois.nic.kw"],
  ky: ["whois.kyreg.com"],
  kyoto: ["whois.nic.kyoto"],
  kz: ["whois.nic.kz"],
  la: ["whois.nic.la"],
  lacaixa: ["whois.nic.lacaixa"],
  lamberts: ["whois.nic.lamberts"],
  land: ["whois.nic.land"],
  landrover: ["whois.nic.landrover"],
  lanxess: ["whois.nic.lanxess"],
  lasalle: ["whois.nic.lasalle"],
  lat: ["whois.nic.lat"],
  latino: ["whois.nic.latino"],
  latrobe: ["whois.nic.latrobe"],
  law: ["whois.nic.law"],
  lawyer: ["whois.nic.lawyer"],
  lb: ["whois.lbdr.org.lb"],
  lc: ["whois2.riponet.re"],
  lds: ["whois.nic.lds"],
  lease: ["whois.nic.lease"],
  leclerc: ["whois.nic.leclerc"],
  lefrak: ["whois.nic.lefrak"],
  legal: ["whois.nic.legal"],
  lego: ["whois.nic.lego"],
  lexus: ["whois.nic.lexus"],
  lgbt: ["whois.afilias-srs.net"],
  li: ["whois.nic.li"],
  lidl: ["whois.nic.lidl"],
  life: ["whois.nic.life"],
  lifeinsurance: ["whois.nic.lifeinsurance"],
  lifestyle: ["whois.nic.lifestyle"],
  lighting: ["whois.nic.lighting"],
  like: ["whois.nic.like"],
  lilly: ["whois.nic.lilly"],
  limited: ["whois.nic.limited"],
  limo: ["whois.nic.limo"],
  lincoln: ["whois.nic.lincoln"],
  linde: ["whois.afilias.net"],
  link: ["whois.nic.link"],
  lipsy: ["whois.nic.lipsy"],
  live: ["whois.nic.live"],
  living: ["whois.nic.living"],
  lixil: ["whois.nic.lixil"],
  lk: ["whois.nic.lk"],
  llc: ["whois.afilias-srs.net"],
  loan: ["whois.nic.loan"],
  loans: ["whois.nic.loans"],
  locker: ["whois.nic.locker"],
  locus: ["whois.nic.locus"],
  loft: ["whois.nic.loft"],
  lol: ["whois.nic.lol"],
  london: ["whois.nic.london"],
  lote: ["whois.nic.lotte"],
  lotto: ["whois.nic.lotto"],
  love: ["whois.nic.love"],
  lpl: ["whois.nic.lpl"],
  lplfinancial: ["whois.nic.lplfinancial"],
  lr: ["whois.nic.lr"],
  ls: ["whois.nic.ls"],
  lt: ["whois.domreg.lt"],
  ltd: ["whois.nic.ltd"],
  lt: ["whois.nic.ltda"],
  lu: ["whois.dns.lu"],
  lun: ["whois.nic.lundbeck"],
  luxe: ["whois.nic.luxe"],
  luxury: ["whois.nic.luxury"],
  lv: ["whois.nic.lv"],
  ly: ["whois.nic.ly"],
  ma: ["whois.iam.net.ma"],
  mack: ["whois.nic.mack"],
  madrid: ["whois.nic.madrid"],
  maif: ["whois.nic.maif"],
  maison: ["whois.nic.maison"],
  make: ["whois.nic.makeup"],
  makeup: ["whois.nic.makeup"],
  man: ["whois.nic.man"],
  management: ["whois.nic.management"],
  mango: ["whois.nic.mango"],
  map: ["whois.nic.map"],
  market: ["whois.nic.market"],
  marketing: ["whois.nic.marketing"],
  markets: ["whois.nic.markets"],
  marriott: ["whois.nic.marriott"],
  marshalls: ["whois.nic.marshalls"],
  maserati: ["whois.nic.maserati"],
  mattel: ["whois.nic.mattel"],
  mba: ["whois.nic.mba"],
  mc: ["whois.ripe.net"],
  mckinsey: ["whois.nic.mckinsey"],
  md: ["whois.nic.md"],
  me: ["whois.nic.me", "whois.meregistry.net", "whois.iana.org"],
  med: ["whois.nic.med"],
  media: ["whois.nic.media"],
  meet: ["whois.nic.meet"],
  melbourne: ["whois.nic.melbourne"],
  meme: ["whois.nic.meme"],
  mem: ["whois.nic.memorial"],
  men: ["whois.nic.men"],
  menu: ["whois.nic.menu"],
  merckmsd: ["whois.nic.merckmsd"],
  mg: ["whois.nic.mg"],
  mh: ["whois.nic.mh"],
  mi: ["whois.nic.mi"],
  mil: ["whois.nic.mil"],
  mini: ["whois.nic.mini"],
  mint: ["whois.nic.mint"],
  mit: ["whois.nic.mit"],
  mitsubishi: ["whois.nic.mitsubishi"],
  mk: ["whois.marnet.mk"],
  ml: ["whois.nic.ml"],
  mlb: ["whois.nic.mlb"],
  mls: ["whois.nic.mls"],
  mm: ["whois.nic.mm"],
  mma: ["whois.nic.mma"],
  mn: ["whois.nic.mn"],
  mo: ["whois.monic.mo"],
  mobi: ["whois.dotmobiregistry.net"],
  mobile: ["whois.nic.mobile"],
  moda: ["whois.nic.moda"],
  moe: ["whois.nic.moe"],
  moi: ["whois.nic.moi"],
  mom: ["whois.nic.mom"],
  monash: ["whois.nic.monash"],
  money: ["whois.nic.money"],
  monster: ["whois.nic.monster"],
  mopar: ["whois.nic.mopar"],
  mordor: ["whois.nic.mormon"],
  mos: ["whois.nic.moscow"],
  mos: ["whois.nic.moto"],
  motorcycle: ["whois.nic.motorcycles"],
  mov: ["whois.nic.movie"],
  mov: ["whois.nic.mp"],
  mq: ["whois.nic.mq"],
  mr: ["whois.nic.mr"],
  ms: ["whois.nic.ms"],
  msd: ["whois.nic.msd"],
  mt: ["whois.nic.org.mt"],
  mtpc: ["whois.nic.mtpc"],
  mtn: ["whois.nic.mtn"],
  mtr: ["whois.nic.mtr"],
  mu: ["whois.nic.mu"],
  museum: ["whois.museum"],
  music: ["whois.nic.music"],
  mv: ["whois.nic.mv"],
  mwc: ["whois.nic.mwc"],
  mx: ["whois.mx"],
  my: ["whois.mynic.my"],
  mz: ["whois.nic.mz"],
  na: ["whois.na-nic.com"],
  nab: ["whois.nic.nab"],
  nagoya: ["whois.nic.nagoya"],
  name: ["whois.nic.name"],
  natsu: ["whois.nic.nationwide"],
  natura: ["whois.nic.natura"],
  navy: ["whois.nic.navy"],
  nba: ["whois.nic.nba"],
  nc: ["whois.nc"],
  ne: ["whois.nic.ne"],
  nec: ["whois.nic.nec"],
  net: ["whois.verisign-grs.com"],
  netbank: ["whois.nic.netbank"],
  netflix: ["whois.nic.netflix"],
  network: ["whois.nic.network"],
  neustar: ["whois.neustar"],
  new: ["whois.nic.new"],
  news: ["whois.nic.news"],
  next: ["whois.nic.next"],
  nextdirect: ["whois.nic.nextdirect"],
  nexus: ["whois.nic.nexus"],
  nf: ["whois.nic.nf"],
  nfl: ["whois.nic.nfl"],
  ng: ["whois.nic.net.ng"],
  ngo: ["whois.pub.nic.ngo"],
  nhk: ["whois.nic.nhk"],
  ni: ["whois.nic.ni"],
  nico: ["whois.nic.nico"],
  nike: ["whois.nic.nike"],
  nikon: ["whois.nic.nikon"],
  ninja: ["whois.nic.ninja"],
  nissan: ["whois.nic.nissan"],
  nissay: ["whois.nic.nissay"],
  nl: ["whois.domain-registry.nl"],
  no: ["whois.norid.no"],
  nokia: ["whois.nic.nokia"],
  northwesternmutual: ["whois.nic.northwesternmutual"],
  norton: ["whois.nic.norton"],
  now: ["whois.nic.now"],
  nowruz: ["whois.nic.nowruz"],
  nowtv: ["whois.nic.nowtv"],
  np: ["whois.nic.np"],
  nr: ["whois.nic.nr"],
  nra: ["whois.nic.nra"],
  nrw: ["whois.nic.nrw"],
  ntt: ["whois.nic.ntt"],
  nu: ["whois.iis.se"],
  nyc: ["whois.nic.nyc"],
  nz: ["whois.srs.net.nz"],
  obi: ["whois.nic.obi"],
  observer: ["whois.nic.observer"],
  off: ["whois.nic.off"],
  office: ["whois.nic.office"],
  okinawa: ["whois.nic.okinawa"],
  olayan: ["whois.nic.olayan"],
  olay: ["whois.nic.olay"],
  oldnavy: ["whois.nic.oldnavy"],
  ollo: ["whois.nic.ollo"],
  om: ["whois.registry.om"],
  omega: ["whois.nic.omega"],
  one: ["whois.nic.one"],
  ong: ["whois.pub.nic.ong"],
  onl: ["whois.nic.onl"],
  online: ["whois.nic.online"],
  ooo: ["whois.nic.ooo"],
  open: ["whois.nic.open"],
  oracle: ["whois.nic.oracle"],
  orange: ["whois.nic.orange"],
  org: ["whois.pir.org"],
  organic: ["whois.nic.organic"],
  origins: ["whois.nic.origins"],
  osaka: ["whois.nic.osaka"],
  ott: ["whois.nic.ott"],
  ovh: ["whois.ovh.net"],
  pa: ["whois.nic.pa"],
  page: ["whois.nic.page"],
  panasonic: ["whois.nic.panasonic"],
  panerai: ["whois.nic.panerai"],
  paris: ["whois.nic.paris"],
  pars: ["whois.nic.pars"],
  partners: ["whois.nic.partners"],
  parts: ["whois.nic.parts"],
  party: ["whois.nic.party"],
  passagens: ["whois.nic.passagens"],
  pay: ["whois.nic.pay"],
  pccw: ["whois.nic.pccw"],
  pe: ["kero.yachay.pe"],
  pet: ["whois.nic.pet"],
  pf: ["whois.registry.pf"],
  pfizer: ["whois.nic.pfizer"],
  pg: ["whois.pngnic.net"],
  ph: ["whois.dot.ph"],
  pharmacy: ["whois.nic.pharmacy"],
  phd: ["whois.nic.phd"],
  philips: ["whois.nic.philips"],
  phone: ["whois.nic.phone"],
  photo: ["whois.nic.photo"],
  photography: ["whois.nic.photography"],
  photos: ["whois.nic.photos"],
  physio: ["whois.nic.physio"],
  pics: ["whois.afilias-srs.net"],
  pictet: ["whois.nic.pictet"],
  pictures: ["whois.nic.pictures"],
  pid: ["whois.nic.pid"],
  pin: ["whois.nic.pin"],
  ping: ["whois.nic.ping"],
  pink: ["whois.nic.pink"],
  pioneer: ["whois.nic.pioneer"],
  pizza: ["whois.nic.pizza"],
  pk: ["whois.pknic.net.pk"],
  pl: ["whois.dns.pl"],
  place: ["whois.nic.place"],
  play: ["whois.nic.play"],
  playstation: ["whois.nic.playstation"],
  plumbing: ["whois.nic.plumbing"],
  plus: ["whois.nic.plus"],
  pm: ["whois.nic.pm"],
  pn: ["whois.nic.pn"],
  pnc: ["whois.nic.pnc"],
  pohl: ["whois.nic.pohl"],
  poker: ["whois.nic.poker"],
  polka: ["whois.nic.polka"],
  pom: ["whois.nic.pom"],
  porn: ["whois.nic.porn"],
  post: ["whois.nic.post"],
  pr: ["whois.pr"],
  pramerica: ["whois.nic.pramerica"],
  prev: ["whois.nic.prevreda"],
  pro: ["whois.afilias-srs.net"],
  prod: ["whois.nic.prod"],
  productions: ["whois.nic.productions"],
  prof: ["whois.nic.prof"],
  progressive: ["whois.nic.progressive"],
  promo: ["whois.nic.promo"],
  properties: ["whois.nic.properties"],
  property: ["whois.nic.property"],
  protection: ["whois.nic.protection"],
  pru: ["whois.nic.pru"],
  prudential: ["whois.nic.prudential"],
  ps: ["whois.pnina.ps"],
  pt: ["whois.dns.pt"],
  pub: ["whois.nic.pub"],
  pw: ["whois.nic.pw"],
  pwc: ["whois.nic.pwc"],
  py: ["whois.nic.py"],
  qa: ["whois.registry.qa"],
  qpon: ["whois.nic.qpon"],
  quebec: ["whois.nic.quebec"],
  quest: ["whois.nic.quest"],
  racing: ["whois.nic.racing"],
  radio: ["whois.nic.radio"],
  read: ["whois.nic.read"],
  realestate: ["whois.nic.realestate"],
  realtor: ["whois.nic.realtor"],
  realty: ["whois.nic.realty"],
  recipes: ["whois.nic.recipes"],
  red: ["whois.afilias-srs.net"],
  redstone: ["whois.nic.redstone"],
  redum: ["whois.nic.reed"],
  reed: ["whois.nic.reed"],
  reise: ["whois.nic.reise"],
  reisen: ["whois.nic.reisen"],
  reit: ["whois.nic.reit"],
  reliance: ["whois.nic.reliance"],
  ren: ["whois.nic.ren"],
  rent: ["whois.nic.rent"],
  rentals: ["whois.nic.rentals"],
  repair: ["whois.nic.repair"],
  report: ["whois.nic.report"],
  republican: ["whois.afilias-srs.net"],
  rest: ["whois.nic.rest"],
  restaurant: ["whois.nic.restaurant"],
  review: ["whois.nic.review"],
  reviews: ["whois.nic.reviews"],
  rexroth: ["whois.nic.rexroth"],
  rich: ["whois.nic.rich"],
  richardli: ["whois.nic.richardli"],
  ricoh: ["whois.nic.ricoh"],
  ril: ["whois.nic.ril"],
  rio: ["whois.nic.rio"],
  rip: ["whois.afilias-srs.net"],
  ro: ["whois.rotld.ro"],
  rocher: ["whois.nic.rocher"],
  rocks: ["whois.nic.rocks"],
  rodeo: ["whois.nic.rodeo"],
  roger: ["whois.nic.rogers"],
  rogers: ["whois.nic.rogers"],
  room: ["whois.nic.room"],
  rs: ["whois.rnids.rs"],
  rsbc: ["whois.nic.rsbc"],
  rsbc: ["whois.nic.ruhr"],
  ru: ["whois.tcinet.ru"],
  rw: ["whois.ricta.org"],
  rwe: ["whois.nic.rwe"],
  ryukyu: ["whois.nic.ryukyu"],
  sa: ["whois.saudinic.net.sa"],
  saarland: ["whois.nic.saarland"],
  safe: ["whois.nic.safe"],
  safety: ["whois.nic.safety"],
  sakura: ["whois.sakura.ad.jp"],
  sale: ["whois.nic.sale"],
  salon: ["whois.nic.salon"],
  samsclub: ["whois.nic.samsclub"],
  samsung: ["whois.nic.samsung"],
  sandvik: ["whois.nic.sandvik"],
  sandvikcoromant: ["whois.nic.sandvikcoromant"],
  sanofi: ["whois.nic.sanofi"],
  sap: ["whois.nic.sap"],
  sarl: ["whois.afilias-srs.net"],
  sas: ["whois.nic.sas"],
  save: ["whois.nic.save"],
  saxo: ["whois.nic.saxo"],
  sb: ["whois.nic.sb"],
  sbi: ["whois.nic.sbi"],
  sbs: ["whois.nic.sbs"],
  sc: ["whois.nic.sc"],
  sca: ["whois.nic.sca"],
  scb: ["whois.nic.scb"],
  scha: ["whois.nic.scholarships"],
  sch: ["whois.schule"],
  schule: ["whois.nic.schule"],
  schwarz: ["whois.nic.schwarz"],
  science: ["whois.nic.science"],
  scot: ["whois.nic.scot"],
  sd: ["whois.nic.sd"],
  se: ["whois.iis.se"],
  search: ["whois.nic.search"],
  seat: ["whois.nic.seat"],
  secure: ["whois.nic.secure"],
  security: ["whois.nic.security"],
  seek: ["whois.nic.seek"],
  select: ["whois.nic.select"],
  sener: ["whois.nic.sener"],
  services: ["whois.nic.services"],
  seven: ["whois.nic.seven"],
  sew: ["whois.nic.sew"],
  sex: ["whois.afilias-srs.net"],
  sexy: ["whois.nic.sexy"],
  sfr: ["whois.nic.sfr"],
  sh: ["whois.nic.sh"],
  shangrila: ["whois.nic.shangrila"],
  sharp: ["whois.nic.sharp"],
  shaw: ["whois.nic.shaw"],
  shell: ["whois.nic.shell"],
  shia: ["whois.nic.shia"],
  shiksha: ["whois.nic.shiksha"],
  shoes: ["whois.nic.shoes"],
  shop: ["whois.nic.shop"],
  shopping: ["whois.nic.shopping"],
  shouji: ["whois.nic.shouji"],
  show: ["whois.nic.show"],
  showtime: ["whois.nic.showtime"],
  shriram: ["whois.nic.shriram"],
  si: ["whois.arnes.si"],
  silk: ["whois.nic.silk"],
  sina: ["whois.nic.sina"],
  singles: ["whois.nic.singles"],
  site: ["whois.nic.site"],
  sj: ["whois.nic.no"],
  sk: ["whois.sk-nic.sk"],
  ski: ["whois.nic.ski"],
  skin: ["whois.nic.skin"],
  sky: ["whois.nic.sky"],
  skype: ["whois.nic.skype"],
  sl: ["whois.nic.sl"],
  sling: ["whois.nic.sling"],
  sm: ["whois.nic.sm"],
  smart: ["whois.nic.smart"],
  smile: ["whois.nic.smile"],
  sn: ["whois.nic.sn"],
  sncf: ["whois.nic.sncf"],
  so: ["whois.nic.so"],
  soccer: ["whois.nic.soccer"],
  social: ["whois.nic.social"],
  softbank: ["whois.nic.softbank"],
  software: ["whois.nic.software"],
  sohu: ["whois.nic.sohu"],
  solar: ["whois.nic.solar"],
  solutions: ["whois.nic.solutions"],
  song: ["whois.nic.song"],
  soon: ["whois.nic.soon"],
  sony: ["whois.nic.sony"],
  soy: ["whois.gandi.net"],
  spa: ["whois.nic.spa"],
  space: ["whois.nic.space"],
  sport: ["whois.nic.sport"],
  spot: ["whois.nic.spot"],
  spreadbetting: ["whois.nic.spreadbetting"],
  sr: ["whois.register.sr"],
  srl: ["whois.afilias-srs.net"],
  srt: ["whois.nic.srt"],
  st: ["whois.nic.st"],
  stada: ["whois.nic.stada"],
  staples: ["whois.nic.staples"],
  star: ["whois.nic.star"],
  starhub: ["whois.nic.starhub"],
  statebank: ["whois.nic.statebank"],
  statefarm: ["whois.nic.statefarm"],
  stc: ["whois.nic.stc"],
  stcgroup: ["whois.nic.stcgroup"],
  stockholm: ["whois.nic.stockholm"],
  storage: ["whois.nic.storage"],
  store: ["whois.nic.store"],
  stream: ["whois.nic.stream"],
  studio: ["whois.nic.studio"],
  study: ["whois.nic.study"],
  style: ["whois.nic.style"],
  su: ["whois.tcinet.ru"],
  sucks: ["whois.nic.sucks"],
  sup: ["whois.nic.sup"],
  supply: ["whois.nic.supply"],
  support: ["whois.nic.support"],
  surf: ["whois.nic.surf"],
  surgery: ["whois.nic.surgery"],
  suzuki: ["whois.nic.suzuki"],
  sv: ["whois.svnet.net.sv"],
  swatch: ["whois.nic.swatch"],
  swif: ["whois.nic.swiftcover"],
  swiftcover: ["whois.nic.swiftcover"],
  sx: ["whois.sx"],
  sy: ["whois.tld.sy"],
  sydney: ["whois.nic.sydney"],
  symantec: ["whois.nic.symantec"],
  systems: ["whois.nic.systems"],
  sz: ["whois.nic.sz"],
  tab: ["whois.nic.tab"],
  tab: ["whois.nic.t-mobile"],
  taiwan: ["whois.nic.taiwan"],
  talk: ["whois.nic.talk"],
  tao: ["whois.nic.taobao"],
  tatar: ["whois.nic.tatar"],
  tat: ["whois.nic.tattoo"],
  tax: ["whois.nic.tax"],
  tci: ["whois.nic.tci"],
  td: ["whois.nic.td"],
  td: ["whois.nic.tdk"],
  team: ["whois.nic.team"],
  tech: ["whois.nic.tech"],
  technology: ["whois.nic.technology"],
  tel: ["whois.nic.tel"],
  temasek: ["whois.nic.temasek"],
  tennis: ["whois.nic.tennis"],
  te: ["whois.nic.teva"],
  tf: ["whois.nic.tf"],
  tg: ["whois.nic.tg"],
  th: ["whois.thnic.co.th"],
  thd: ["whois.nic.thd"],
  theater: ["whois.nic.theater"],
  theatre: ["whois.nic.theatre"],
  tiaa: ["whois.nic.tiaa"],
  tickets: ["whois.nic.tickets"],
  tienda: ["whois.nic.tienda"],
  tips: ["whois.nic.tips"],
  tires: ["whois.nic.tires"],
  tirol: ["whois.nic.tirol"],
  tj: ["whois.nic.tj"],
  tjx: ["whois.nic.tjx"],
  tk: ["whois.dot.tk"],
  tl: ["whois.nic.tl"],
  tm: ["whois.nic.tm"],
  tn: ["whois.ati.tn"],
  to: ["whois.tonic.to"],
  today: ["whois.nic.today"],
  tokyo: ["whois.nic.tokyo"],
  tools: ["whois.nic.tools"],
  top: ["whois.nic.top"],
  toray: ["whois.nic.toray"],
  toshiba: ["whois.nic.toshiba"],
  total: ["whois.nic.total"],
  tours: ["whois.nic.tours"],
  town: ["whois.nic.town"],
  toyota: ["whois.nic.toyota"],
  toys: ["whois.nic.toys"],
  tr: ["whois.nic.tr"],
  trade: ["whois.nic.trade"],
  trading: ["whois.nic.trading"],
  training: ["whois.nic.training"],
  travel: ["whois.nic.travel"],
  travelchannel: ["whois.nic.travelchannel"],
  travelers: ["whois.nic.travelers"],
  travelersinsurance: ["whois.nic.travelersinsurance"],
  trust: ["whois.nic.trust"],
  trv: ["whois.nic.trv"],
  tt: ["whois.nic.tt"],
  tube: ["whois.nic.tube"],
  tui: ["whois.nic.tui"],
  tun: ["whois.nic.tunes"],
  tushu: ["whois.nic.tushu"],
  tv: ["whois.nic.tv"],
  tvs: ["whois.nic.tvs"],
  tw: ["whois.twnic.net.tw"],
  tz: ["whois.tznic.or.tz"],
  ua: ["whois.ua"],
  ubank: ["whois.nic.ubank"],
  ubs: ["whois.nic.ubs"],
  uconnect: ["whois.nic.uconnect"],
  ug: ["whois.co.ug"],
  uk: ["whois.nic.uk"],
  unicom: ["whois.nic.unicom"],
  university: ["whois.nic.university"],
  uno: ["whois.nic.uno"],
  uol: ["whois.host.uol.com.br"],
  ups: ["whois.nic.ups"],
  us: ["whois.nic.us"],
  uy: ["whois.nic.org.uy"],
  uz: ["whois.cctld.uz"],
  va: ["whois.vatican.va"],
  vacations: ["whois.nic.vacations"],
  van: ["whois.nic.vlaanderen"],
  vegas: ["whois.nic.vegas"],
  ve: ["whois.nic.ve"],
  versicherung: ["whois.nic.versicherung"],
  vet: ["whois.afilias-srs.net"],
  vg: ["whois.nic.vg"],
  vi: ["whois.nic.vi"],
  viajes: ["whois.nic.viajes"],
  video: ["whois.nic.video"],
  vig: ["whois.nic.vig"],
  vikings: ["whois.nic.vikings"],
  villas: ["whois.nic.villas"],
  vin: ["whois.nic.vin"],
  vip: ["whois.nic.vip"],
  virgin: ["whois.nic.virgin"],
  visa: ["whois.nic.visa"],
  vision: ["whois.nic.vision"],
  vista: ["whois.nic.vista"],
  vistaprint: ["whois.nic.vistaprint"],
  vita: ["whois.nic.vita"],
  viv: ["whois.nic.viv"],
  viv: ["whois.nic.vivo"],
  vlaanderen: ["whois.nic.vlaanderen"],
  vn: ["whois.vnnic.vn"],
  vodka: ["whois.nic.vodka"],
  volkswagen: ["whois.nic.volkswagen"],
  volvo: ["whois.nic.volvo"],
  vote: ["whois.afilias-srs.net"],
  voting: ["whois.afilias-srs.net"],
  voto: ["whois.nic.voto"],
  voyages: ["whois.nic.voyages"],
  vu: ["whois.nic.vu"],
  wales: ["whois.nic.wales"],
  walmart: ["whois.nic.walmart"],
  walter: ["whois.nic.walter"],
  wang: ["whois.nic.wang"],
  wanggou: ["whois.nic.wanggou"],
  watch: ["whois.nic.watch"],
  watches: ["whois.nic.watches"],
  weather: ["whois.nic.weather"],
  weatherchannel: ["whois.nic.weatherchannel"],
  webcam: ["whois.nic.webcam"],
  weber: ["whois.nic.weber"],
  website: ["whois.nic.website"],
  wed: ["whois.nic.wed"],
  wedding: ["whois.nic.wedding"],
  we: ["whois.nic.weddings"],
  weibo: ["whois.nic.weibo"],
  weir: ["whois.nic.weir"],
  wf: ["whois.nic.wf"],
  whoswho: ["whois.nic.whoswho"],
  wien: ["whois.nic.wien"],
  wiki: ["whois.nic.wiki"],
  williamhill: ["whois.nic.williamhill"],
  win: ["whois.nic.win"],
  windows: ["whois.nic.windows"],
  wine: ["whois.nic.wine"],
  winners: ["whois.nic.winners"],
  wme: ["whois.nic.wme"],
  wolterskluwer: ["whois.nic.wolterskluwer"],
  woodside: ["whois.nic.woodside"],
  work: ["whois.nic.work"],
  works: ["whois.nic.works"],
  world: ["whois.nic.world"],
  wow: ["whois.nic.wow"],
  ws: ["whois.nic.ws"],
  wtc: ["whois.nic.wtc"],
  wv: ["whois.nic.wvu"],
  wvu: ["whois.nic.wvu"],
  xbox: ["whois.nic.xbox"],
  xerox: ["whois.nic.xerox"],
  xgma: ["whois.nic.xgma"],
  xihuan: ["whois.nic.xihuan"],
  xin: ["whois.nic.xin"],
  xn--11b4c3d: ["whois.nic.ไทย"], // .ไทย
  xn--1ck2e1b: ["whois.sgnic.sg"], // .新加坡
  xn--1qqw23a: ["whois.cnnic.cn"], // .中国
  xn--2scrj9c: ["whois.nic.გე"], // .გე
  xn--30rr7y: ["whois.nic.am"], // .հայ
  xn--3bst00m: ["whois.nic.集团"], // .集团
  xn--3ds443g: ["whois.nic.在线"], // .在线
  xn--3e0b707e: ["whois.nic.한국"], // .한국
  xn--3hcrj9c: ["whois.marnet.mk"], // .мкд
  xn--3pxu8k: ["whois.nic.网络"], // .网络
  xn--42c2d9a: ["whois.nic.இந்தியா"], // .இந்தியா
  xn--45br5cyl: ["whois.nic.مصر"], // .مصر
  xn--45brj9c: ["whois.isoc.org.il"], // .ישראל
  xn--45q11c: ["whois.nic.中国"], // .中国
  xn--4dbrk0ce: ["whois.nic.հայ"], // .հայ
  xn--4gbrim: ["whois.ua"], // .укр
  xn--54b7fta0cc: ["whois.nic.भारत"], // .भारत
  xn--55qw42g: ["whois.nic.公益"], // .公益
  xn--55qx5d: ["whois.cnnic.cn"], // .公司
  xn--5su34j3a: ["whois.nic.台灣"], // .台灣
  xn--5tzm5g: ["whois.nic.شبكة"], // .شبكة
  xn--6frz82g: ["whois.afilias-srs.net"], // .中信
  xn--6qq986b3xl: ["whois.gname.net"], // .我爱你
  xn--80akhbyknj4f: ["whois.nic.рф"], // .рф
  xn--80ao21a: ["whois.nic.קום"], // .קום
  xn--80aqecdr1a: ["whois.nic.پاکستان"], // .پاکستان
  xn--80asehdb: ["whois.imena.ru"], // .рус
  xn--80aswg: ["whois.nic.срб"], // .срб
  xn--8y0a063a: ["whois.nic.澳門"], // .澳門
  xn--90a3ac: ["whois.nic.срб"], // .срб
  xn--90ae: ["whois.nic.бел"], // .бел
  xn--90ais: ["whois.eu.org"], // .ευ
  xn--9dbq2a: ["whois.nic.قطر"], // .قطر
  xn--9et52u: ["whois.nic.大园"], // .大园
  xn--9krt00a: ["whois.nic.بيت"], // .بيت
  xn--b4w605ferd: ["whois.nic.مملكة"], // .مملكة
  xn--bck1b9a5dre4c: ["whois.nic.გე"], // .გე
  xn--c1avg: ["whois.imena.ru"], // .москва
  xn--c2br7g: ["whois.nic.在线"], // .在线
  xn--cck2b3b: ["whois.nic.アリババ"], // .アリババ
  xn--cckwcxetd: ["whois.nic.八卦"], // .八卦
  xn--cg4bki: ["whois.nic.政务"], // .政务
  xn--clchc0ea0b2g2a9gcd: ["whois.sgnic.sg"], // .新加坡
  xn--czr694b: ["whois.hkirc.hk"], // .香港
  xn--czrs0t: ["whois.nic.ไทย"], // .ไทย
  xn--czru2d: ["whois.nic.مملكة"], // .مملكة
  xn--d1acj3b: ["whois.nic.рф"], // .рф
  xn--d1alf: ["whois.marnet.mk"], // .мкд
  xn--e1a4c: ["whois.nic.дети"], // .дети
  xn--eckvdtc9d: ["whois.nic.नेट"], // .नेट
  xn--efvy88h: ["whois.nic.سعودي"], // .سعودي
  xn--fct429k: ["whois.nic.中原"], // .中原
  xn--fhbei: ["whois.nic.新闻"], // .新闻
  xn--fiq228c5hs: ["whois.nic.中国"], // .中国
  xn--fiq64b: ["whois.cnnic.cn"], // .中文网
  xn--fiqs8s: ["whois.cnnic.cn"], // .中国
  xn--fiqz9s: ["whois.cnnic.cn"], // .网络
  xn--fjq720a: ["whois.nic.公司"], // .公司
  xn--flw351e: ["whois.hkirc.hk"], // .香港
  xn--fpcrj9c3d: ["whois.nic.لندن"], // .لندن
  xn--fzc2c9e2c: ["whois.nic.لائوس"], // .لائوس
  xn--fzys8d69uvgm: ["whois.nic.مصر"], // .مصر
  xn--g2xx48c: ["whois.nic.公益"], // .公益
  xn--gckr3f0f: ["whois.nic.政府"], // .政府
  xn--gecrj9c: ["whois.nic.ком"], // .ком
  xn--gk3at1e: ["whois.nic.台湾"], // .台湾
  xn--h2breg3eve: ["whois.nic.هم"], // .هم
  xn--h2brj9c: ["whois.nic.عرب"], // .عرب
  xn--h2brj9c8c: ["whois.nic.الاردن"], // .الاردن
  xn--hxt814e: ["whois.nic.中文"], // .中文
  xn--i1b6b1a6a2e: ["whois.nic.ไทย"], // .ไทย
  xn--imr1d: ["whois.nic.蒙"], // .蒙
  xn--io0a7i: ["whois.nic.云"], // .云
  xn--j1aef: ["whois.nic.аэропорт"], // .аэропорт
  xn--j1amh: ["whois.nic.онлайн"], // .онлайн
  xn--j6w193g: ["whois.hkirc.hk"], // .香港
  xn--jlq480n2rg: ["whois.nic.公益"], // .公益
  xn--jlq61u9w7b: ["whois.nic.爱"], // .爱
  xn--jvr189m: ["whois.nic.网店"], // .网店
  xn--kcrx77d1x4b: ["whois.nic.广东"], // .广东
  xn--kprw13d: ["whois.nic.世界"], // .世界
  xn--kpry57d: ["whois.nic.政务"], // .政务
  xn--kput3i: ["whois.nic.香格里拉"], // .香格里拉
  xn--l1acc: ["whois.nic.сайт"], // .сайт
  xn--lgbr52d: ["whois.nic.娱乐"], // .娱乐
  xn--mgbab2bd: ["whois.nic.بازار"], // .بازار
  xn--mgbab2bd: ["whois.nic.موقع"], // .موقع
  xn--mgbayh7gpa: ["whois.registry.om"], // .عمان
  xn--mgbbh1a: ["whois.nic.السعودية"], // .السعودية
  xn--mgbbh1a71e: ["whois.nic.السعودية"], // .السعودية
  xn--mgbc0a9azcg: ["whois.nic.pk"], // .پاکستان
  xn--mgbca7dzdo: ["whois.nic.شبكة"], // .شبكة
  xn--mgbcpq6gpa1a88zcd: ["whois.nic.مملكة"], // .مملكة
  xn--mgberp4a5d4ar: ["whois.registry.qa"], // .قطر
  xn--mgbgu82a: ["whois.nic.تك"], // .تك
  xn--mgbi4ecexp: ["whois.nic.امارات"], // .امارات
  xn--mgbpl2fh: ["whois.nic.sa"], // .السعودية
  xn--mgbtx2b: ["whois.nic.كوم"], // .كوم
  xn--mgbx4cd0ab: ["whois.cmc.iq"], // .عراق
  xn--mix891f: ["whois.cnnic.cn"], // .中文网
  xn--mk1bu44c: ["whois.nic.니"], // .니
  xn--mxtq1m: ["whois.nic.公益"], // .公益
  xn--ngbc5azd: ["whois.nic.موريتانيا"], // .موريتانيا
  xn--ngbe9e0a: ["whois.nic.مصر"], // .مصر
  xn--ngbrx: ["whois.nic.تونس"], // .تونس
  xn--node: ["whois.nic.政府"], // .政府
  xn--nqv7f: ["whois.nic.网络"], // .网络
  xn--nqv7fs00bar: ["whois.nic.公司"], // .公司
  xn--p1ai: ["whois.nic.ru"], // .рф
  xn--pgbs0dh: ["whois.nic.台湾"], // .台湾
  xn--pssy2u: ["whois.nic.大拿"], // .大拿
  xn--q7ce6a: ["whois.nic.流动"], // .流动
  xn--q9jyb4c: ["whois.nic.みんな"], // .みんな
  xn--qcka1pmc: ["whois.nic.ググッ"], // .ググッ
  xn--qxam: ["whois.nic.عراق"], // .عراق
  xn--rhqv96g: ["whois.nic.忠安"], // .忠安
  xn--rovu88b: ["whois.nic.商城"], // .商城
  xn--rvc1e0am3e: ["whois.nic.प्रदेश"], // .प्रदेश
  xn--s9brj9c: ["whois.nic.বাংলা"], // .বাংলা
  xn--ses554g: ["whois.nic.信息"], // .信息
  xn--t60b56a: ["whois.nic.닷컴"], // .닷컴
  xn--tckwe: ["whois.nic.कॉम"], // .कॉम
  xn--tiq49xqyj: ["whois.nic.公益"], // .公益
  xn--unup4y: ["whois.godaddy.com"], // .游戏
  xn--vermgensberater-ctb: ["whois.nic.vermgensberater"], // .vermgensberater
  xn--vermgensberatung-pwb: ["whois.nic.vermgensberatung"], // .vermgensberatung
  xn--vhquv: ["whois.nic.公益"], // .公益
  xn--vuq861b: ["whois.nic.集团"], // .集团
  xn--w4r85el8fhu5dnra: ["whois.nic.泰国"], // .泰国
  xn--w4rs40l: ["whois.nic.ไทย"], // .ไทย
  xn--wgbh1c: ["whois.nic.琦"], // .琦
  xn--wgbl6a: ["whois.nic.مواقع"], // .مواقع
  xn--xhq521b: ["whois.gname.net"], // .游戏
  xn--xkc2al3hye2a: ["whois.nic.巴哈马"], // .巴哈马
  xn--xkc2dl3a5ee0h: ["whois.nic.台湾"], // .台湾
  xn--y9a3aq: ["whois.nic.花儿"], // .花儿
  xn--yfro4i67o: ["whois.nic.香港"], // .香港
  xn--ygbi2ammx: ["whois.nic.موبايل"], // .موبايل
  xn--zfr164b: ["whois.nic.みんな"], // .みんな
  xpcom: ["whois.nic.xn--gckr3f0f"],
  xxx: ["whois.nic.xxx"],
  xyz: ["whois.nic.xyz"],
  yacht: ["whois.nic.yacht"],
  yahoo: ["whois.nic.yahoo"],
  yamaxun: ["whois.nic.yamaxun"],
  yandex: ["whois.nic.yandex"],
  ye: ["whois.y.net.ye"],
  yodobashi: ["whois.nic.yodobashi"],
  yoga: ["whois.nic.yoga"],
  yokohama: ["whois.nic.yokohama"],
  you: ["whois.nic.you"],
  youtube: ["whois.nic.youtube"],
  yt: ["whois.nic.yt"],
  yun: ["whois.nic.yun"],
  za: ["whois.registry.net.za"],
  zappos: ["whois.nic.zappos"],
  zara: ["whois.nic.zara"],
  zero: ["whois.nic.zero"],
  zip: ["whois.nic.zip"],
  zm: ["whois.nic.zm"],
  zone: ["whois.nic.zone"],
  zuerich: ["whois.nic.zuerich"],
  zw: ["whois.registry.net.zw"],
  // Note: This is a comprehensive list based on IANA data as of 2025. For exact current details, query whois.iana.org.
}

export function getWhoisServers(domain: string): string[] {
  const parts = domain.toLowerCase().split(".")
  if (parts.length < 2) return []

  const tld = parts[parts.length - 1]

  // Direct lookup for ASCII TLDs
  let servers = WHOIS_SERVERS[tld as keyof typeof WHOIS_SERVERS]
  if (servers && servers.length > 0) {
    return servers
  }

  // For punycode TLDs (xn--*), try direct lookup
  if (tld.startsWith("xn--")) {
    servers = WHOIS_SERVERS[tld as keyof typeof WHOIS_SERVERS]
    if (servers && servers.length > 0) {
      return servers
    }
  }

  return []
}

export function isWhoisSupported(domain: string): boolean {
  return getWhoisServers(domain).length > 0
}
